openapi: 3.0.0
info:
  title: BriteNotes API
  contact:
    email: engineering@britecore.com
  version: '0.1'

tags:
  - name: notes
    description: BriteNotes Operations

paths:
  /notes:
    get:
      description: Lists all notes
      operationId: getNotes
      responses:
        '200':
          description: Notes successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      tags:
        - notes
      summary: Adds a new note
      operationId: addNote
      description: Adds a new note
      responses:
        '201':
          description: Note successfully created
  /notes/{id}:
    get:
      tags:
        - notes
      summary: Gets a specific note
      operationId: getNote
      description: Gets a specific note
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier for retrieving single object
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Note successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    patch:
      tags:
        - notes
      summary: Partially updates a note
      operationId: partiallyUpdateNote
      description: Updates one or more fields of a note
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Note successfully updated
    put:
      tags:
        - notes
      summary: Updates a note
      operationId: updateNote
      description: Update note
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Note successfully updated
    delete:
      tags:
        - notes
      summary: Deletes an existing note
      operationId: deleteNote
      description: Deletes an existing note
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Note successfully deleted
components:
  schemas:
    Note:
      type: object
      required:
        - creator
        - reference
        - title
      properties:
        creator:
          type: string
          description: AWS Cognito ID of the note creator
        title:
          type: string
          description: The note title
        reference:
          type: object
          description: Information about the entity to which the note belongs to
          properties:
            id:
              type: string
              format: uuid
              description: The reference's immutable identifier
            label:
              type: string
              description: The reference's application-level mutable identifier
            domain:
              type: string
              description: The domain to which the reference belongs to
            level:
              type: string
              description: The level inside the domain
        body:
          type: string
